# Generated by Django 2.2.6 on 2020-12-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('uid', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=511)),
                ('rating', models.FloatField(default=0.0)),
                ('release_date', models.CharField(max_length=511)),
                ('director', models.CharField(max_length=511)),
                ('actors', models.CharField(max_length=511)),
                ('runtime', models.CharField(max_length=511)),
                ('plot', models.TextField(blank=True)),
                ('votes', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='episodes.Episode')),
            ],
        ),
    ]
